cargo-features = ["different-binary-name"]

[package]
name = "mlua-macros"
version = "0.1.0"
edition = "2021"

[lib]
name = "moonbind"
crate-type = ["cdylib"] 

[dependencies]
mlua = {version="0.8.6", features=["lua54", "module"]}
mlua-derive = {path = "mlua-derive"}